### ISSUE TITLE
Rework architecture react-app (using atomic-design)

### ISSUE THREAD

**Issue by greatpersonn** [AdaY45/explorium-client#5]
# Already created

# Now in work
- [ ] Rework react-app architecture
- [ ] Create small (atoms), molecules (medium), organism (large) element
# Almost ready

# Tasks
- [ ] Create several templates, which we can use in future
- [ ] Create main pages react-app with help of template
